connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://postgresql:5432/dhis
connection.username = dhis
connection.password = dhis
connection.schema = update

hibernate.show_sql = true
hibernate.format_sql = true

# WORKS!
route.remote_servers_allowed=http://*
# route.remote_servers_allowed=http://*,https://*
# route.remote_servers_allowed=http://host.docker.internal:8000
# route.remote_servers_allowed=http://host.docker.internal:8000,https://host.docker.internal:8000

# Allowed route URL must not have a path: http://host.docker.internal:8000/
# route.remote_servers_allowed=http://host.docker.internal:8000/
# route.remote_servers_allowed=http://host.docker.internal:8000/,https://host.docker.internal:8000/
